In [8]:
import numpy as np
import pandas as pd
import yfinance as yf

# Explore what data we can get

In [21]:
company = "MSFT"
stock = yf.Ticker("MSFT")

In [25]:
stock.history(period="1mo").tail()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-02-19 00:00:00-05:00,407.063806,414.658563,406.834255,413.940002,24114200,0.00,0.0
2025-02-20 00:00:00-05:00,415.290009,419.309998,412.540009,416.130005,23508700,0.83,0.0
2025-02-21 00:00:00-05:00,417.339996,418.049988,407.890015,408.209991,27524800,0.00,0.0
2025-02-24 00:00:00-05:00,408.510010,409.369995,399.320007,404.000000,26443700,0.00,0.0
2025-02-25 00:00:00-05:00,401.100006,401.920013,396.700012,397.899994,29318100,0.00,0.0

Everyday stock prices, include:
- Open, high, low, close: obvious
- Volume: Amount of stock exchanged
- Dividends: Paid on that date if exists, else 0
- Stock splits: Is when a company increases the number of shares outstanding by dividing its existing shares. The price of each share decreases, but the total shareholder value remains the same.

For example:
ðŸ”¹ 2-for-1 split: If you have 1 share of stock worth 200, after the split, you will have 2 shares worth 100 each.

So these are the columns we are gonna try to predict

In [27]:
stock.option_chain(dat.options[0]).calls.tail()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
64,MSFT250228C00525000,2025-01-30 17:45:47+00:00,525.0,0.07,0.0,0.50,0.0,0.0,20.0,34,1.367191,False,REGULAR,USD
65,MSFT250228C00530000,2025-02-14 15:25:23+00:00,530.0,0.01,0.0,0.21,0.0,0.0,3.0,6,1.265629,False,REGULAR,USD
66,MSFT250228C00540000,2025-02-07 19:32:08+00:00,540.0,0.02,0.0,0.21,0.0,0.0,5.0,21,1.335941,False,REGULAR,USD
67,MSFT250228C00550000,2025-02-07 18:58:41+00:00,550.0,0.01,0.0,0.01,0.0,0.0,3.0,45,1.062505,False,REGULAR,USD
68,MSFT250228C00560000,2025-02-24 17:03:38+00:00,560.0,0.01,0.0,0.01,0.0,0.0,1.0,183,1.125004,False,REGULAR,USD

Not really understand those columns so comeback later

In [32]:
stock.balance_sheet.head()

,2024-06-30,2023-06-30,2022-06-30,2021-06-30
Ordinary Shares Number,7434138859.0,7432000000.0,7464000000.0,7519000000.0
Share Issued,7434138859.0,7432000000.0,7464000000.0,7519000000.0
Net Debt,33315000000.0,12533000000.0,35850000000.0,43922000000.0
Total Debt,67127000000.0,59965000000.0,61270000000.0,67775000000.0
Tangible Book Value,121660000000.0,128971000000.0,87720000000.0,84477000000.0

In [35]:
stock.balance_sheet.shape

(78, 4)

In [36]:
columns = stock.balance_sheet.index
columns

Index(['Ordinary Shares Number', 'Share Issued', 'Net Debt', 'Total Debt',
       'Tangible Book Value', 'Invested Capital', 'Working Capital',
       'Net Tangible Assets', 'Capital Lease Obligations',
       'Common Stock Equity', 'Total Capitalization',
       'Total Equity Gross Minority Interest', 'Stockholders Equity',
       'Gains Losses Not Affecting Retained Earnings',
       'Other Equity Adjustments', 'Retained Earnings', 'Capital Stock',
       'Common Stock', 'Total Liabilities Net Minority Interest',
       'Total Non Current Liabilities Net Minority Interest',
       'Other Non Current Liabilities', 'Tradeand Other Payables Non Current',
       'Non Current Deferred Liabilities', 'Non Current Deferred Revenue',
       'Non Current Deferred Taxes Liabilities',
       'Long Term Debt And Capital Lease Obligation',
       'Long Term Capital Lease Obligation', 'Long Term Debt',
       'Current Liabilities', 'Other Current Liabilities',
       'Current Deferred Liabilities', 'Current Deferred Revenue',
       'Current Debt And Capital Lease Obligation', 'Current Debt',
       'Other Current Borrowings', 'Commercial Paper',
       'Pensionand Other Post Retirement Benefit Plans Current',
       'Payables And Accrued Expenses', 'Payables', 'Total Tax Payable',
       'Income Tax Payable', 'Accounts Payable', 'Total Assets',
       'Total Non Current Assets', 'Other Non Current Assets',
       'Financial Assets', 'Investments And Advances',
       'Investmentin Financial Assets', 'Available For Sale Securities',
       'Long Term Equity Investment', 'Goodwill And Other Intangible Assets',
       'Other Intangible Assets', 'Goodwill', 'Net PPE',
       'Accumulated Depreciation', 'Gross PPE', 'Leases', 'Other Properties',
       'Machinery Furniture Equipment', 'Buildings And Improvements',
       'Land And Improvements', 'Properties', 'Current Assets',
       'Other Current Assets', 'Hedging Assets Current', 'Inventory',
       'Finished Goods', 'Work In Process', 'Raw Materials', 'Receivables',
       'Accounts Receivable', 'Allowance For Doubtful Accounts Receivable',
       'Gross Accounts Receivable',
       'Cash Cash Equivalents And Short Term Investments',
       'Other Short Term Investments', 'Cash And Cash Equivalents',
       'Cash Equivalents', 'Cash Financial'],
      dtype='object')

Those yearly report should be useful

In [39]:
stock.quarterly_income_stmt.head()

,2024-12-31,2024-09-30,2024-06-30,2024-03-31,2023-12-31
Tax Effect Of Unusual Items,-203220000.0,57190000.0,-16263853.211009,-33660000.0,-29160000.0
Tax Rate For Calcs,0.18,0.19,0.191339,0.18,0.18
Normalized EBITDA,37915000000.0,37933000000.0,34416000000.0,33741000000.0,33556000000.0
Total Unusual Items,-1129000000.0,301000000.0,-85000000.0,-187000000.0,-162000000.0
Total Unusual Items Excluding Goodwill,-1129000000.0,301000000.0,-85000000.0,-187000000.0,-162000000.0

In [40]:
stock.quarterly_income_stmt.shape

(47, 5)

In [41]:
stock.quarterly_income_stmt.index

Index(['Tax Effect Of Unusual Items', 'Tax Rate For Calcs',
       'Normalized EBITDA', 'Total Unusual Items',
       'Total Unusual Items Excluding Goodwill',
       'Net Income From Continuing Operation Net Minority Interest',
       'Reconciled Depreciation', 'Reconciled Cost Of Revenue', 'EBITDA',
       'EBIT', 'Net Interest Income', 'Interest Expense', 'Interest Income',
       'Normalized Income',
       'Net Income From Continuing And Discontinued Operation',
       'Total Expenses', 'Total Operating Income As Reported',
       'Diluted Average Shares', 'Basic Average Shares', 'Diluted EPS',
       'Basic EPS', 'Diluted NI Availto Com Stockholders',
       'Net Income Common Stockholders', 'Net Income',
       'Net Income Including Noncontrolling Interests',
       'Net Income Continuous Operations', 'Tax Provision', 'Pretax Income',
       'Other Income Expense', 'Other Non Operating Income Expenses',
       'Special Income Charges', 'Write Off', 'Gain On Sale Of Security',
       'Net Non Operating Interest Income Expense',
       'Interest Expense Non Operating', 'Interest Income Non Operating',
       'Operating Income', 'Operating Expense', 'Research And Development',
       'Selling General And Administration', 'Selling And Marketing Expense',
       'General And Administrative Expense', 'Other Gand A', 'Gross Profit',
       'Cost Of Revenue', 'Total Revenue', 'Operating Revenue'],
      dtype='object')

# Load data

In [16]:
tickers = ["MSFT", "AAPL", "TSLA", "GOOGL", "AMZN", "NVDA"]

In [20]:
data = []

for ticker in tickers:
    print("Company: ", ticker)
    stock = yf.Ticker(ticker)
    # print(stock.history(period="1mo"))
    print(stock.balance_sheet)
    
    # data.append({
    #     "Ticker": ticker,
    #     "Company": info.get("shortName", "N/A"),
    #     "Sector": info.get("sector", "N/A"),
    #     "Market Cap (USD)": info.get("marketCap", "N/A"),
    #     "PE Ratio": info.get("trailingPE", "N/A"),
    #     "EPS": info.get("trailingEps", "N/A"),
    #     "52 Week High": info.get("fiftyTwoWeekHigh", "N/A"),
    #     "52 Week Low": info.get("fiftyTwoWeekLow", "N/A"),
    #     "Dividend Yield": info.get("dividendYield", "N/A")
    # })

# df = pd.DataFrame(data)
# df.head()

Company:  MSFT
                                                      2024-06-30  \
Ordinary Shares Number                              7434138859.0
Share Issued                                        7434138859.0
Net Debt                                           33315000000.0
Total Debt                                         67127000000.0
Tangible Book Value                               121660000000.0
...                                                          ...
Cash Cash Equivalents And Short Term Investments   75531000000.0
Other Short Term Investments                       57216000000.0
Cash And Cash Equivalents                          18315000000.0
Cash Equivalents                                    6744000000.0
Cash Financial                                     11571000000.0

                                                      2023-06-30  \
Ordinary Shares Number                              7432000000.0
Share Issued                                        7432000000.0
Net Debt                                           12533000000.0
Total Debt                                         59965000000.0
Tangible Book Value                               128971000000.0
...                                                          ...
Cash Cash Equivalents And Short Term Investments  111256000000.0
Other Short Term Investments                       76552000000.0
Cash And Cash Equivalents                          34704000000.0
Cash Equivalents                                   26226000000.0
Cash Financial                                      8478000000.0

                                                      2022-06-30  \
Ordinary Shares Number                              7464000000.0
Share Issued                                        7464000000.0
Net Debt                                           35850000000.0
Total Debt                                         61270000000.0
Tangible Book Value                                87720000000.0
...                                                          ...
Cash Cash Equivalents And Short Term Investments  104749000000.0
Other Short Term Investments                       90818000000.0
Cash And Cash Equivalents                          13931000000.0
Cash Equivalents                                    5673000000.0
Cash Financial                                      8258000000.0

                                                      2021-06-30
Ordinary Shares Number                              7519000000.0
Share Issued                                        7519000000.0
Net Debt                                           43922000000.0
Total Debt                                         67775000000.0
Tangible Book Value                                84477000000.0
...                                                          ...
Cash Cash Equivalents And Short Term Investments  130256000000.0
Other Short Term Investments                      116032000000.0
Cash And Cash Equivalents                          14224000000.0
Cash Equivalents                                    6952000000.0
Cash Financial                                      7272000000.0

[78 rows x 4 columns]
Company:  AAPL
                                                      2024-09-30  \
Treasury Shares Number                                       NaN
Ordinary Shares Number                             15116786000.0
Share Issued                                       15116786000.0
Net Debt                                           76686000000.0
Total Debt                                        106629000000.0
...                                                          ...
Cash Cash Equivalents And Short Term Investments   65171000000.0
Other Short Term Investments                       35228000000.0
Cash And Cash Equivalents                          29943000000.0
Cash Equivalents                                    2744000000.0
Cash Financial                                     27199000000.0

                                                      2023-09-30  \
Treasury Shares Number                                       0.0
Ordinary Shares Number                             15550061000.0
Share Issued                                       15550061000.0
Net Debt                                           81123000000.0
Total Debt                                        111088000000.0
...                                                          ...
Cash Cash Equivalents And Short Term Investments   61555000000.0
Other Short Term Investments                       31590000000.0
Cash And Cash Equivalents                          29965000000.0
Cash Equivalents                                    1606000000.0
Cash Financial                                     28359000000.0

                                                      2022-09-30  \
Treasury Shares Number                                       NaN
Ordinary Shares Number                             15943425000.0
Share Issued                                       15943425000.0
Net Debt                                           96423000000.0
Total Debt                                        132480000000.0
...                                                          ...
Cash Cash Equivalents And Short Term Investments   48304000000.0
Other Short Term Investments                       24658000000.0
Cash And Cash Equivalents                          23646000000.0
Cash Equivalents                                    5100000000.0
Cash Financial                                     18546000000.0

                                                      2021-09-30 2020-09-30
Treasury Shares Number                                       NaN        NaN
Ordinary Shares Number                             16426786000.0        NaN
Share Issued                                       16426786000.0        NaN
Net Debt                                           89779000000.0        NaN
Total Debt                                        136522000000.0        NaN
...                                                          ...        ...
Cash Cash Equivalents And Short Term Investments   62639000000.0        NaN
Other Short Term Investments                       27699000000.0        NaN
Cash And Cash Equivalents                          34940000000.0        NaN
Cash Equivalents                                   17635000000.0        NaN
Cash Financial                                     17305000000.0        NaN

[68 rows x 5 columns]
Company:  TSLA
                                                     2024-12-31  \
Treasury Shares Number                                      NaN
Ordinary Shares Number                             3216000000.0
Share Issued                                       3216000000.0
Total Debt                                        13623000000.0
Tangible Book Value                               71443000000.0
...                                                         ...
Cash Cash Equivalents And Short Term Investments  36563000000.0
Other Short Term Investments                      20424000000.0
Cash And Cash Equivalents                         16139000000.0
Cash Equivalents                                   1753000000.0
Cash Financial                                    14386000000.0

                                                     2023-12-31  \
Treasury Shares Number                                      0.0
Ordinary Shares Number                             3185000000.0
Share Issued                                       3185000000.0
Total Debt                                         9573000000.0
Tangible Book Value                               62019000000.0
...                                                         ...
Cash Cash Equivalents And Short Term Investments  29094000000.0
Other Short Term Investments                      12696000000.0
Cash And Cash Equivalents                         16398000000.0
Cash Equivalents                                    495000000.0
Cash Financial                                    15903000000.0

                                                     2022-12-31  \
Treasury Shares Number                                      NaN
Ordinary Shares Number                             3164000000.0
Share Issued                                       3164000000.0
Total Debt                                         5748000000.0
Tangible Book Value                               44111000000.0
...                                                         ...
Cash Cash Equivalents And Short Term Investments  22185000000.0
Other Short Term Investments                       5932000000.0
Cash And Cash Equivalents                         16253000000.0
Cash Equivalents                                   2288000000.0
Cash Financial                                    13965000000.0

                                                     2021-12-31 2020-12-31
Treasury Shares Number                                      NaN        NaN
Ordinary Shares Number                             3099000000.0        NaN
Share Issued                                       3099000000.0        NaN
Total Debt                                         8873000000.0        NaN
Tangible Book Value                               28472000000.0        NaN
...                                                         ...        ...
Cash Cash Equivalents And Short Term Investments  17707000000.0        NaN
Other Short Term Investments                        131000000.0        NaN
Cash And Cash Equivalents                         17576000000.0        NaN
Cash Equivalents                                   9548000000.0        NaN
Cash Financial                                     8028000000.0        NaN

[81 rows x 5 columns]
Company:  GOOGL
                                                      2024-12-31  \
Treasury Shares Number                                       NaN
Ordinary Shares Number                             12211000000.0
Share Issued                                       12211000000.0
Total Debt                                         25461000000.0
Tangible Book Value                               293199000000.0
...                                                          ...
Allowance For Doubtful Accounts Receivable          -879000000.0
Gross Accounts Receivable                          53219000000.0
Cash Cash Equivalents And Short Term Investments   95657000000.0
Other Short Term Investments                       72191000000.0
Cash And Cash Equivalents                          23466000000.0

                                                      2023-12-31  \
Treasury Shares Number                                       0.0
Ordinary Shares Number                             12460000000.0
Share Issued                                       12460000000.0
Total Debt                                         27121000000.0
Tangible Book Value                               254181000000.0
...                                                          ...
Allowance For Doubtful Accounts Receivable          -771000000.0
Gross Accounts Receivable                          48735000000.0
Cash Cash Equivalents And Short Term Investments  110916000000.0
Other Short Term Investments                       86868000000.0
Cash And Cash Equivalents                          24048000000.0

                                                      2022-12-31  \
Treasury Shares Number                                       NaN
Ordinary Shares Number                             12849000000.0
Share Issued                                       12849000000.0
Total Debt                                         29679000000.0
Tangible Book Value                               227184000000.0
...                                                          ...
Allowance For Doubtful Accounts Receivable          -754000000.0
Gross Accounts Receivable                          41012000000.0
Cash Cash Equivalents And Short Term Investments  113762000000.0
Other Short Term Investments                       91883000000.0
Cash And Cash Equivalents                          21879000000.0

                                                      2021-12-31 2020-12-31
Treasury Shares Number                                       NaN        NaN
Ordinary Shares Number                             13242420000.0        NaN
Share Issued                                       13242420000.0        NaN
Total Debt                                         28395000000.0        NaN
Tangible Book Value                               227262000000.0        NaN
...                                                          ...        ...
Allowance For Doubtful Accounts Receivable          -550000000.0        NaN
Gross Accounts Receivable                          39854000000.0        NaN
Cash Cash Equivalents And Short Term Investments  139649000000.0        NaN
Other Short Term Investments                      118704000000.0        NaN
Cash And Cash Equivalents                          20945000000.0        NaN

[75 rows x 5 columns]
Company:  AMZN
                                                      2024-12-31  \
Treasury Shares Number                               515000000.0
Ordinary Shares Number                             10593000000.0
Share Issued                                       11108000000.0
Net Debt                                                     NaN
Total Debt                                        130900000000.0
...                                                          ...
Allowance For Doubtful Accounts Receivable         -2000000000.0
Gross Accounts Receivable                          57451000000.0
Cash Cash Equivalents And Short Term Investments  101202000000.0
Other Short Term Investments                       22423000000.0
Cash And Cash Equivalents                          78779000000.0

                                                      2023-12-31  \
Treasury Shares Number                               515000000.0
Ordinary Shares Number                             10383000000.0
Share Issued                                       10898000000.0
Net Debt                                                     NaN
Total Debt                                        135611000000.0
...                                                          ...
Allowance For Doubtful Accounts Receivable         -1700000000.0
Gross Accounts Receivable                          53953000000.0
Cash Cash Equivalents And Short Term Investments   86780000000.0
Other Short Term Investments                       13393000000.0
Cash And Cash Equivalents                          73387000000.0

                                                      2022-12-31  \
Treasury Shares Number                               515000000.0
Ordinary Shares Number                             10242000000.0
Share Issued                                       10757000000.0
Net Debt                                           13262000000.0
Total Debt                                        140118000000.0
...                                                          ...
Allowance For Doubtful Accounts Receivable         -1400000000.0
Gross Accounts Receivable                          43760000000.0
Cash Cash Equivalents And Short Term Investments   70026000000.0
Other Short Term Investments                       16138000000.0
Cash And Cash Equivalents                          53888000000.0

                                                      2021-12-31 2020-12-31
Treasury Shares Number                               460000000.0        NaN
Ordinary Shares Number                             10180000000.0        NaN
Share Issued                                       10640000000.0        NaN
Net Debt                                           12524000000.0        NaN
Total Debt                                        116395000000.0        NaN
...                                                          ...        ...
Allowance For Doubtful Accounts Receivable         -1100000000.0        NaN
Gross Accounts Receivable                          33991000000.0        NaN
Cash Cash Equivalents And Short Term Investments   96049000000.0        NaN
Other Short Term Investments                       59829000000.0        NaN
Cash And Cash Equivalents                          36220000000.0        NaN

[61 rows x 5 columns]
Company:  NVDA
                                                     2024-01-31  \
Treasury Shares Number                                      NaN
Ordinary Shares Number                            24640000000.0
Share Issued                                      24640000000.0
Net Debt                                           2429000000.0
Total Debt                                        11056000000.0
...                                                         ...
Allowance For Doubtful Accounts Receivable                  NaN
Gross Accounts Receivable                                   NaN
Cash Cash Equivalents And Short Term Investments  25984000000.0
Other Short Term Investments                      18704000000.0
Cash And Cash Equivalents                          7280000000.0

                                                     2023-01-31  \
Treasury Shares Number                                      NaN
Ordinary Shares Number                            24661365720.0
Share Issued                                      24661365720.0
Net Debt                                           7564000000.0
Total Debt                                        12031000000.0
...                                                         ...
Allowance For Doubtful Accounts Receivable                  NaN
Gross Accounts Receivable                                   NaN
Cash Cash Equivalents And Short Term Investments  13296000000.0
Other Short Term Investments                       9907000000.0
Cash And Cash Equivalents                          3389000000.0

                                                     2022-01-31     2021-01-31
Treasury Shares Number                                      NaN  13800000000.0
Ordinary Shares Number                            25060000000.0  24800000000.0
Share Issued                                      25060000000.0  38600000000.0
Net Debt                                           8956000000.0   6116000000.0
Total Debt                                        11831000000.0   7597000000.0
...                                                         ...            ...
Allowance For Doubtful Accounts Receivable                  NaN    -21000000.0
Gross Accounts Receivable                                   NaN   2450000000.0
Cash Cash Equivalents And Short Term Investments  21208000000.0  11561000000.0
Other Short Term Investments                      19218000000.0  10714000000.0
Cash And Cash Equivalents                          1990000000.0    847000000.0

[83 rows x 4 columns]

# Helper function

In [5]:
def calculate_stats(data, columns):
    if isinstance(columns, str):
        columns = [columns]

    stats = []
    for col in columns:
        if data[col].dtype in ['object', 'category']:
            counts = data[col].value_counts(dropna=False, sort=False)
            percents = data[col].value_counts(normalize=True, dropna=False, sort=False) * 100
            formatted = counts.astype(str) + ' (' + percents.round(2).astype(str) + '%)'
            stats_col = pd.DataFrame({'count (%)': formatted})
            stats.append(stats_col)
        else:
            stats_col = data[col].describe().to_frame().transpose()
            stats_col['missing'] = data[col].isnull().sum()
            stats_col.index.name = col
            stats.append(stats_col)

    return pd.concat(stats, axis=0)